### ISSUE TITLE
Cannot upload MS Teams attendance list for attendance check

### ISSUE THREAD

**Issue by cragkhit** [ICT-Mahidol/ICTClassManagement#4]
Hi. I uploaded the MS Teams attendance file (attached) using the "import" button. However, the system showed the "error file format"
[meetingAttendanceReport(1_Lectures).csv](https://github.com/ICT-Mahidol/ICTClassManagement/files/7948864/meetingAttendanceReport.1_Lectures.csv)
![CleanShot 2565-01-27 at 15 29 19@2x](https://user-images.githubusercontent.com/1671353/151321145-3125d6e1-d1b1-425c-b19f-e921ae073f1d.png)
![CleanShot 2565-01-27 at 15 29 27@2x](https://user-images.githubusercontent.com/1671353/151321154-e9adb6d9-235c-4dd0-8af9-9bc9882d33b7.png)
![CleanShot 2565-01-27 at 15 29 31@2x](https://user-images.githubusercontent.com/1671353/151321166-e52f29f3-4457-4be5-a143-9e86ae7eaf2a.png)
.

**Comment by siripenp** [comment]
@cragkhit  Thank you very much for your information. The CSV that you shared has an invalid format. The file from MS Teams that we support has to be downloaded from "participants list" menu. This is not the same as attendance report. 

After releasing this feature, we later realized that MS teams also provided another kind of report after the end of the meeting. 

Sorry that the system doesn't support that report just yet ka. This is still in our to-do list. >~<

**Comment by cragkhit** [comment]
@siripenp Oh I see. Thanks for the clarification. I guess the participants list cannot be retrieved after the meeting has ended, right? I'll wait for the next update then 😄

**Comment by cragkhit** [comment]
[Week4 - Business Process and Functional Modeling  - Attendance Report 1-27-22.csv](https://github.com/ICT-Mahidol/ICTClassManagement/files/8038797/Week4.-.Business.Process.and.Functional.Modeling.-.Attendance.Report.1-27-22.csv)
I tried uploading the attendance report (attached) but it also didn't work. Could you please advise krub? @siripenp

**Comment by siripenp** [comment]
![image](https://user-images.githubusercontent.com/25128248/153522546-f2ea9b1a-20c4-4458-83d3-2fae122d6f67.png)
@cragkhit  Here is the format that will work. The file name is something like "meetingAttendanceList.csv". It is not an attendance report. Did you get this report by downloading it from the participant menu? If so, probably MS team has already changed the format. I will check again today after my class na ka. Sorry for an inconvenience ka

**Comment by cragkhit** [comment]
@siripenp I see. I'm not sure krub. I could no longer find the download option from the participants menu so I downloaded from the meeting detail page instead (attached). Thanks!
![CleanShot 2565-02-11 at 10 07 26@2x](https://user-images.githubusercontent.com/1671353/153532013-8d9399f1-6523-4b9a-a5e6-f71b1d2dcb84.png)

**Comment by siripenp** [comment]
@cragkhit Aj.Aun we have good news. Now you can import the Attendance Report from MS Teams =D

A format like this should work. Could you please check. The one report that can be downloaded after class dismissed.

![image](https://user-images.githubusercontent.com/25128248/155273091-479b5a38-06ef-4b7b-a7bd-85598315b126.png)

**Comment by cragkhit** [comment]
@siripenp Thanks a lot for adding this feature. I tried and it worked perfectly! 👏 Well done krub!
